language: node_js
cache: yarn
node_js:
  - node
  - lts/*
script: yarn ci
jobs:
  include:
    - stage: semantic-release
      if: branch = master
      node_js: node
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn release
